name: CI/CD AWS Lambda com Terraform (Aprimorado)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  # ARN do Role assumido pelo GitHub Actions para o deploy
  # O valor está armazenado no GitHub Secrets
  ROLE_TO_ASSUME: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
  
jobs:
  terraform:
    name: 'Terraform Plan & Apply'
    runs-on: ubuntu-latest
    permissions: # PERMISSÕES PARA O OIDC
      id-token: write # Permite gerar o JWT necessário para assumir o Role na AWS
      contents: read  # Permissão padrão para fazer o checkout do código
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 3. Corrigir Formatação (Garante que a sintaxe esteja ok)
    - name: Corrigir Formatação
      id: fmt
      run: terraform fmt -recursive

    # 4. Inicializa o Backend (S3 + DynamoDB Lock)
    - name: Terraform Init
      id: init
      run: terraform init

    # 5. ETAPA TEMPORÁRIA: Re-importar a função existente (REMOVER APÓS O SUCESSO)
    - name: 5.1. Forçar Remoção de Estado e Re-Importar Função
      id: import_lambda
      run: |
        # 1. Tenta remover o recurso do estado. O '|| true' garante que o pipeline não pare se o recurso já não estiver no estado.
        terraform state rm aws_lambda_function.minha_funcao_tf || true
        # 2. Re-importa o recurso existente para garantir a sincronização.
        terraform import -no-color -input=false aws_lambda_function.minha_funcao_tf chatbot-fiscal-processor
        # OBS: Remova este passo inteiro após o sucesso!

    # 6. Gera o Plano (Plan)
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color -input=false -out=tfplan
      
    # 7. Aplica o Plano (Apply) - Apenas na branch main
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
